### PR TITLE
Update the deploy details screenshot

### PR DESCRIPTION
**Pull request by ntith**

### CODE REVIEW

**Comment by emuus** [comment]
Changing image is ok with me. However, we may want to add a note at the end of this page : http://docs.usharesoft.com/projects/appcenter-user-guide/en/latest/pages/templating/deploy-machine-image.html to explain that the deployment can be deleted. And explain if deleting the deployment only deletes the instance on UForge or also stops and deletes the instance deployed.

**Comment by ntith** [comment]
does this note already exist? 
capture d ecran de 2018-03-08 15-34-43

**Comment by emuus** [comment]
Good point. If the action is the same then one note will be enough. However, maybe we should rephrase the note : If you click on the delete (garbage) icon, this will stop your deployed instance and remove it from your cloud.
I believe originally we added the note because the question was "how do we stop a running instance" (the answer was to delete it from the first screen). But now we are answering the question : what does the garbage icon do.

**Comment by ntith** [comment]
ok so I will change the note using your new sentence, and provide another commit
Thanks @emuus

**Pull request merged**
