### PR TITLE
Add other K5 specific instructions 

### PR DESCRIPTION
**Pull request by cinlloc**
Have to disable NLA for K5 before golden creation and Windows blackbox migration.

_Note: I didn't find any Microsoft official documentation about how to do this, so I've put another article. Do you think it can do it or do we have to write a specific doc for this?_

### CODE REVIEW

**Comment by mstenz** [comment]
External information can be changed or removed. If there is some information that can be easily rewritten I like this more.

**Comment by mstenz** [comment]
Here is the documentation from Microsoft about NLA:
https://technet.microsoft.com/en-us/library/cc732713(v=ws.11).aspx

**Comment by cinlloc** [comment]
Thanks Michael for the link. I've seen this link but I found it less clear than the other article. Nevertheless, it's sure Technet articles are more official and surely more stable in time. So I will change it.

**Comment by emuus** [comment]
Yes, best to use official MS documentation if available. Users will search other forums for more clarity if needed. I would suggest : Disable NLA for RDP (refer to official Microsoft Documentation (Configure Network Level Authentication for Remote Desktop Services Connections) ... The title is long, but including it allows users to search more easily for it, in case the link is broken, or article is moved.

**Comment by emuus** [comment]
Thanks for these last changes. Ok for me.

**Pull request merged**
