### PR TITLE
add some notes about licenses of RHEL and Windows

### PR DESCRIPTION
**Pull request by omishima**

### CODE REVIEW

**Comment by emuus** [comment]
Thank you for your changes. Please make sure to compile and check the html results before re-submitting.

**Comment by omishima** [comment]
Thank you for your reviewing. I have reflected the matters pointed out. Please confirm them.

**Comment by emuus** [comment]
The text changes are ok. If you have compiled (make clean ; make html) and there are no errors due to indenting, then ok for me. Again thank you for your contribution.

**Comment by omishima** [comment]
OK, I've found no problem. Compiling done successfully and no error outputted.

**Pull request merged**
